version: '3'
services:
  backend:
    build:
      context: ./calculadora_metodos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./calculadora_metodos:/app

  frontend:
    build:
      context: ./front_Calculadora./vite-project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge