version: '3'
services:
  metodo_biseccion:
    build:
      context: ./calculadora_metodos/Metodo_Biseccion
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  metodo_broyden:
    build:
      context: ./calculadora_metodos/Metodo_Broyden
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    networks:
      - app-network

  metodo_newton_raphson:
    build:
      context: ./calculadora_metodos/Metodo_Newton_Raphson
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    networks:
      - app-network

  metodo_punto_fijo:
    build:
      context: ./calculadora_metodos/Metodo_Punto_Fijo
      dockerfile: Dockerfile
    ports:
      - "5201:5201"
    networks:
      - app-network

  metodo_secante:
    build:
      context: ./calculadora_metodos/Metodo_Secante
      dockerfile: Dockerfile
    ports:
      - "5400:5400"
    networks:
      - app-network

  metodo_jacobi:
    build:
      context: ./calculadora_metodos/Metodo_Jacobi
      dockerfile: Dockerfile
    ports:
      - "5501:5501"
    networks:
      - app-network

  metodo_gauss:
    build:
      context: ./calculadora_metodos/Metodo_Gauss_Seidel
      dockerfile: Dockerfile
    ports:
      - "5502:5502"
    networks:
      - app-network

  metodo_gauss:
    build:
      context: ./calculadora_metodos/Metodo_Trapecio
      dockerfile: Dockerfile
    ports:
      - "5503:5503"
    networks:
      - app-network

  frontend:
    build:
      context: ./front_Calculadora
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - metodo_biseccion
      - metodo_broyden
      - metodo_newton_raphson
      - metodo_punto_fijo
      - metodo_secante
      - metodo_jacobi
      - metodo_gauss
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
